name: MagicPlayer
version: ${projectVersion}
main: com.magicrealms.magicplayer.core.BukkitMagicPlayer
api-version: 1.21
author: Ryan0916
commands:
  MagicPlayer:
    description: '魔法领域-玩家'
    aliases:
      - online
      - avatar
      - profile
      - setting
depend:
  - MagicLib
  - SkinsRestorer
